services:
  nginx:
    image: "nginx"
    # ports:
    #   - "80:80"
    #   - "5000:5000"
    #   - "4998:4998"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/etc/nginx/logs
      - ./nginx/html:/etc/nginx/html
    network_mode: host



      