services:
  app:
    image: ghcr.io/hongjicai/organizer:latest
    ports:
      - "81:80"
    volumes:
      - ${COMIC_PATH}:/data/comics
      - ${VIDEO_PATH}:/data/videos
      - ${IMAGE_PATH}:/data/images
      - ${LIKED_PATH}:/data/liked
      - ./config:/config
    restart: unless-stopped
