services:
  app:
    image: ghcr.io/hongjicai/organizer:latest
    ports:
      - "80:80"
    volumes:
      - ${COMIC_PATH}:/data/comics
      - ${VIDEO_PATH}:/data/videos
      - ${IMAGE_PATH:-/tmp/images}:/data/images
      - ./data/db:/data/db
    restart: unless-stopped
