// This file is auto-generated by @hey-api/openapi-ts

export const APIMessageSchema = {
    properties: {
        detail: {
            type: 'string',
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['detail'],
    title: 'APIMessage',
    description: 'A lightweight utility class intended for use with simple message-returning endpoints.'
} as const;

export const AuthStatusResponseSchema = {
    properties: {
        required: {
            type: 'boolean',
            title: 'Required'
        }
    },
    type: 'object',
    required: ['required'],
    title: 'AuthStatusResponse'
} as const;

export const BackupInfoSchema = {
    properties: {
        last_backup: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Backup'
        },
        backup_count: {
            type: 'integer',
            title: 'Backup Count',
            default: 0
        },
        cadence_hours: {
            type: 'integer',
            title: 'Cadence Hours',
            default: 24
        }
    },
    type: 'object',
    title: 'BackupInfo'
} as const;

export const CheckRequestSchema = {
    properties: {
        ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Ids',
            description: 'Entity ids to probe'
        }
    },
    type: 'object',
    required: ['ids'],
    title: 'CheckRequest',
    description: 'Request to re-verify on disk whether the backing files still exist.'
} as const;

export const CheckResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/CheckResult'
            },
            type: 'array',
            title: 'Results'
        }
    },
    type: 'object',
    required: ['results'],
    title: 'CheckResponse',
    description: 'Response for a batch file-existence check.'
} as const;

export const CheckResultSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['id', 'status'],
    title: 'CheckResult',
    description: `Per-id result of a file-existence check.

\`\`status\`\` is one of:
* \`\`present\`\`  — file is back on disk; the \`\`missing\`\` flag was cleared
* \`\`absent\`\`   — file is confirmed gone; the \`\`missing\`\` flag was set
* \`\`unknown\`\`  — could not be determined (mount blip); flag left untouched
* \`\`notfound\`\` — no such id in the database`
} as const;

export const ComicDetailResponseSchema = {
    properties: {
        pageDetails: {
            items: {
                '$ref': '#/components/schemas/ComicPageDetailResponse'
            },
            type: 'array',
            title: 'Pagedetails'
        }
    },
    type: 'object',
    required: ['pageDetails'],
    title: 'ComicDetailResponse',
    description: 'Response for comic details'
} as const;

export const ComicEntitySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        updateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Updatetime'
        },
        archived: {
            type: 'boolean',
            title: 'Archived',
            default: false
        },
        favorited: {
            type: 'boolean',
            title: 'Favorited',
            default: false
        },
        missing: {
            type: 'boolean',
            title: 'Missing',
            default: false
        },
        lastViewedTime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lastviewedtime'
        },
        lastViewedPosition: {
            type: 'integer',
            title: 'Lastviewedposition',
            default: 0
        },
        coverPosition: {
            type: 'integer',
            title: 'Coverposition',
            default: 0
        },
        entityUpdateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Entityupdatetime'
        },
        page: {
            type: 'integer',
            title: 'Page',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'size', 'name', 'path', 'updateTime'],
    title: 'ComicEntity'
} as const;

export const ComicPageDetailResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ComicPageDetailResponse',
    description: 'Response for comic page details'
} as const;

export const ComicRenameRequestSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ComicRenameRequest',
    description: 'Request to rename a comic'
} as const;

export const ComicRenameResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ComicRenameResponse',
    description: 'Response for comic rename operation'
} as const;

export const DailyScanInfoSchema = {
    properties: {
        scan_hour: {
            type: 'integer',
            title: 'Scan Hour'
        },
        next_run: {
            type: 'string',
            title: 'Next Run'
        }
    },
    type: 'object',
    required: ['scan_hour', 'next_run'],
    title: 'DailyScanInfo'
} as const;

export const FavorResponseSchema = {
    properties: {
        favorited: {
            type: 'boolean',
            title: 'Favorited'
        }
    },
    type: 'object',
    required: ['favorited'],
    title: 'FavorResponse',
    description: 'Response for favor/unfavor operations'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['status', 'message'],
    title: 'HealthResponse'
} as const;

export const ImageDetailResponseSchema = {
    properties: {
        pageDetails: {
            items: {
                '$ref': '#/components/schemas/ImagePageDetailResponse'
            },
            type: 'array',
            title: 'Pagedetails'
        }
    },
    type: 'object',
    required: ['pageDetails'],
    title: 'ImageDetailResponse'
} as const;

export const ImageEntitySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        updateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Updatetime'
        },
        archived: {
            type: 'boolean',
            title: 'Archived',
            default: false
        },
        favorited: {
            type: 'boolean',
            title: 'Favorited',
            default: false
        },
        missing: {
            type: 'boolean',
            title: 'Missing',
            default: false
        },
        lastViewedTime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lastviewedtime'
        },
        lastViewedPosition: {
            type: 'integer',
            title: 'Lastviewedposition',
            default: 0
        },
        coverPosition: {
            type: 'integer',
            title: 'Coverposition',
            default: 0
        },
        entityUpdateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Entityupdatetime'
        },
        page: {
            type: 'integer',
            title: 'Page',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'size', 'name', 'path', 'updateTime'],
    title: 'ImageEntity'
} as const;

export const ImagePageDetailResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ImagePageDetailResponse'
} as const;

export const ImageRenameRequestSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ImageRenameRequest'
} as const;

export const ImageRenameResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ImageRenameResponse'
} as const;

export const LoginRequestSchema = {
    properties: {
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['password'],
    title: 'LoginRequest'
} as const;

export const LoginResponseSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'LoginResponse'
} as const;

export const ProgressRequestSchema = {
    properties: {
        position: {
            type: 'integer',
            minimum: 1,
            title: 'Position',
            description: '1-based page position'
        }
    },
    type: 'object',
    required: ['position'],
    title: 'ProgressRequest',
    description: 'Request to update reading progress'
} as const;

export const ProgressResponseSchema = {
    properties: {
        position: {
            type: 'integer',
            title: 'Position'
        },
        lastViewedTime: {
            type: 'string',
            format: 'date-time',
            title: 'Lastviewedtime'
        }
    },
    type: 'object',
    required: ['position', 'lastViewedTime'],
    title: 'ProgressResponse',
    description: 'Response for reading progress update'
} as const;

export const ScanResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['status', 'message'],
    title: 'ScanResponse'
} as const;

export const ScanStatusResponseSchema = {
    properties: {
        running: {
            type: 'boolean',
            title: 'Running'
        },
        media_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Type'
        },
        phase: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phase'
        },
        total: {
            type: 'integer',
            title: 'Total',
            default: 0
        },
        processed: {
            type: 'integer',
            title: 'Processed',
            default: 0
        },
        reconciled: {
            type: 'integer',
            title: 'Reconciled',
            default: 0
        },
        started_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        timing: {
            '$ref': '#/components/schemas/ScanTiming'
        },
        last_result: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Result'
        }
    },
    type: 'object',
    required: ['running', 'timing'],
    title: 'ScanStatusResponse'
} as const;

export const ScanTimingSchema = {
    properties: {
        count: {
            type: 'integer',
            title: 'Count'
        },
        avg_ms: {
            type: 'number',
            title: 'Avg Ms'
        },
        p95_ms: {
            type: 'number',
            title: 'P95 Ms'
        },
        slowest: {
            items: {
                '$ref': '#/components/schemas/SlowFile'
            },
            type: 'array',
            title: 'Slowest'
        }
    },
    type: 'object',
    required: ['count', 'avg_ms', 'p95_ms', 'slowest'],
    title: 'ScanTiming'
} as const;

export const SlowFileSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        ms: {
            type: 'number',
            title: 'Ms'
        }
    },
    type: 'object',
    required: ['path', 'ms'],
    title: 'SlowFile'
} as const;

export const TasksResponseSchema = {
    properties: {
        daily_scan: {
            '$ref': '#/components/schemas/DailyScanInfo'
        },
        backup: {
            '$ref': '#/components/schemas/BackupInfo'
        }
    },
    type: 'object',
    required: ['daily_scan', 'backup'],
    title: 'TasksResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VideoEntitySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        updateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Updatetime'
        },
        archived: {
            type: 'boolean',
            title: 'Archived',
            default: false
        },
        favorited: {
            type: 'boolean',
            title: 'Favorited',
            default: false
        },
        missing: {
            type: 'boolean',
            title: 'Missing',
            default: false
        },
        lastViewedTime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lastviewedtime'
        },
        lastViewedPosition: {
            type: 'integer',
            title: 'Lastviewedposition',
            default: 0
        },
        coverPosition: {
            type: 'integer',
            title: 'Coverposition',
            default: 0
        },
        entityUpdateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Entityupdatetime'
        },
        durationInSecond: {
            type: 'integer',
            title: 'Durationinsecond',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'size', 'name', 'path', 'updateTime'],
    title: 'VideoEntity'
} as const;

export const MessageResponseSchema = {
    type: 'object',
    properties: {
        msg: {
            type: 'string',
            title: 'Msg'
        }
    },
    required: ['msg'],
    title: 'MessageResponse'
} as const;