// This file is auto-generated by @hey-api/openapi-ts

export const APIMessageSchema = {
    properties: {
        detail: {
            type: 'string',
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['detail'],
    title: 'APIMessage',
    description: 'A lightweight utility class intended for use with simple message-returning endpoints.'
} as const;

export const AuthStatusResponseSchema = {
    properties: {
        required: {
            type: 'boolean',
            title: 'Required'
        }
    },
    type: 'object',
    required: ['required'],
    title: 'AuthStatusResponse'
} as const;

export const ComicDetailResponseSchema = {
    properties: {
        pageDetails: {
            items: {
                '$ref': '#/components/schemas/ComicPageDetailResponse'
            },
            type: 'array',
            title: 'Pagedetails'
        }
    },
    type: 'object',
    required: ['pageDetails'],
    title: 'ComicDetailResponse',
    description: 'Response for comic details'
} as const;

export const ComicEntitySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        updateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Updatetime'
        },
        archived: {
            type: 'boolean',
            title: 'Archived',
            default: false
        },
        favorited: {
            type: 'boolean',
            title: 'Favorited',
            default: false
        },
        lastViewedTime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lastviewedtime'
        },
        lastViewedPosition: {
            type: 'integer',
            title: 'Lastviewedposition',
            default: 0
        },
        coverPosition: {
            type: 'integer',
            title: 'Coverposition',
            default: 0
        },
        entityUpdateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Entityupdatetime'
        },
        page: {
            type: 'integer',
            title: 'Page',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'size', 'name', 'path', 'updateTime'],
    title: 'ComicEntity'
} as const;

export const ComicPageDetailResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ComicPageDetailResponse',
    description: 'Response for comic page details'
} as const;

export const ComicRenameRequestSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ComicRenameRequest',
    description: 'Request to rename a comic'
} as const;

export const ComicRenameResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ComicRenameResponse',
    description: 'Response for comic rename operation'
} as const;

export const FavorResponseSchema = {
    properties: {
        favorited: {
            type: 'boolean',
            title: 'Favorited'
        }
    },
    type: 'object',
    required: ['favorited'],
    title: 'FavorResponse',
    description: 'Response for favor/unfavor operations'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['status', 'message'],
    title: 'HealthResponse'
} as const;

export const ImageDetailResponseSchema = {
    properties: {
        pageDetails: {
            items: {
                '$ref': '#/components/schemas/ImagePageDetailResponse'
            },
            type: 'array',
            title: 'Pagedetails'
        }
    },
    type: 'object',
    required: ['pageDetails'],
    title: 'ImageDetailResponse'
} as const;

export const ImageEntitySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        updateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Updatetime'
        },
        archived: {
            type: 'boolean',
            title: 'Archived',
            default: false
        },
        favorited: {
            type: 'boolean',
            title: 'Favorited',
            default: false
        },
        lastViewedTime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lastviewedtime'
        },
        lastViewedPosition: {
            type: 'integer',
            title: 'Lastviewedposition',
            default: 0
        },
        coverPosition: {
            type: 'integer',
            title: 'Coverposition',
            default: 0
        },
        entityUpdateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Entityupdatetime'
        },
        page: {
            type: 'integer',
            title: 'Page',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'size', 'name', 'path', 'updateTime'],
    title: 'ImageEntity'
} as const;

export const ImagePageDetailResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ImagePageDetailResponse'
} as const;

export const ImageRenameRequestSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ImageRenameRequest'
} as const;

export const ImageRenameResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ImageRenameResponse'
} as const;

export const LoginRequestSchema = {
    properties: {
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['password'],
    title: 'LoginRequest'
} as const;

export const LoginResponseSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'LoginResponse'
} as const;

export const ScanResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['status', 'message'],
    title: 'ScanResponse'
} as const;

export const ScanStatusResponseSchema = {
    properties: {
        running: {
            type: 'boolean',
            title: 'Running'
        },
        last_result: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Result'
        }
    },
    type: 'object',
    required: ['running'],
    title: 'ScanStatusResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VideoEntitySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        updateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Updatetime'
        },
        archived: {
            type: 'boolean',
            title: 'Archived',
            default: false
        },
        favorited: {
            type: 'boolean',
            title: 'Favorited',
            default: false
        },
        lastViewedTime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lastviewedtime'
        },
        lastViewedPosition: {
            type: 'integer',
            title: 'Lastviewedposition',
            default: 0
        },
        coverPosition: {
            type: 'integer',
            title: 'Coverposition',
            default: 0
        },
        entityUpdateTime: {
            type: 'string',
            format: 'date-time',
            title: 'Entityupdatetime'
        },
        durationInSecond: {
            type: 'integer',
            title: 'Durationinsecond',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'size', 'name', 'path', 'updateTime'],
    title: 'VideoEntity'
} as const;

export const MessageResponseSchema = {
    type: 'object',
    properties: {
        msg: {
            type: 'string',
            title: 'Msg'
        }
    },
    required: ['msg'],
    title: 'MessageResponse'
} as const;