// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { StatusData, StatusResponse, StatusError, LoginData, LoginResponse2, LoginError, ComicGetAllData, ComicGetAllResponse, ComicGetAllError, ComicCheckData, ComicCheckResponse, ComicCheckError, ComicDeleteData, ComicDeleteError, ComicGetData, ComicGetResponse, ComicGetError, ComicDetailData, ComicDetailResponse2, ComicDetailError, ComicUnfavorData, ComicUnfavorResponse, ComicUnfavorError, ComicFavorData, ComicFavorResponse, ComicFavorError, ComicRefreshData, ComicRefreshResponse, ComicRefreshError, ComicRenameData, ComicRenameResponse2, ComicRenameError, ComicPageGetData, ComicPageGetError, ComicPageUpdateProgressData, ComicPageUpdateProgressResponse, ComicPageUpdateProgressError, ComicPageLikeData, ComicPageLikeError, ComicPageSetCoverData, ComicPageSetCoverError, VideoGetAllData, VideoGetAllResponse, VideoGetAllError, VideoDeleteData, VideoDeleteResponse, VideoDeleteError, VideoGetData, VideoGetResponse, VideoGetError, ImageGetAllData, ImageGetAllResponse, ImageGetAllError, ImageDeleteData, ImageDeleteResponse, ImageDeleteError, ImageGetData, ImageGetResponse, ImageGetError, ImageDetailData, ImageDetailResponse2, ImageDetailError, ImageDeletePageData, ImageDeletePageResponse, ImageDeletePageError, ImageGetPageData, ImageGetPageError, ImageUpdateProgressData, ImageUpdateProgressResponse, ImageUpdateProgressError, ImageUnfavorData, ImageUnfavorResponse, ImageUnfavorError, ImageFavorData, ImageFavorResponse, ImageFavorError, ImageRefreshData, ImageRefreshResponse, ImageRefreshError, ImageRenameData, ImageRenameResponse2, ImageRenameError, ImageSetCoverData, ImageSetCoverError, ImageConvertData, ImageConvertResponse, ImageConvertError, HealthCheckData, HealthCheckResponse, HealthCheckError, ScanStatusData, ScanStatusResponse2, ScanStatusError, TriggerScanData, TriggerScanResponse, TriggerScanError, TasksStatusData, TasksStatusResponse, TasksStatusError, TriggerBackupData, TriggerBackupResponse, TriggerBackupError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AuthService {
    /**
     * Status
     */
    public static status<ThrowOnError extends boolean = false>(options?: Options<StatusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<StatusResponse, StatusError, ThrowOnError>({
            url: '/api/auth/status',
            ...options
        });
    }
    
    /**
     * Login
     */
    public static login<ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<LoginResponse2, LoginError, ThrowOnError>({
            url: '/api/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class ComicsService {
    /**
     * Comiccbv.Get All
     */
    public static comicGetAll<ThrowOnError extends boolean = false>(options?: Options<ComicGetAllData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<ComicGetAllResponse, ComicGetAllError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics',
            ...options
        });
    }
    
    /**
     * Comiccbv.Check
     */
    public static comicCheck<ThrowOnError extends boolean = false>(options: Options<ComicCheckData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ComicCheckResponse, ComicCheckError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/check',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Comiccbv.Delete
     */
    public static comicDelete<ThrowOnError extends boolean = false>(options: Options<ComicDeleteData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<unknown, ComicDeleteError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}',
            ...options
        });
    }
    
    /**
     * Comiccbv.Get
     */
    public static comicGet<ThrowOnError extends boolean = false>(options: Options<ComicGetData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<ComicGetResponse, ComicGetError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}',
            ...options
        });
    }
    
    /**
     * Comiccbv.Detail
     */
    public static comicDetail<ThrowOnError extends boolean = false>(options: Options<ComicDetailData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<ComicDetailResponse2, ComicDetailError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}/detail',
            ...options
        });
    }
    
    /**
     * Comiccbv.Unfavor
     */
    public static comicUnfavor<ThrowOnError extends boolean = false>(options: Options<ComicUnfavorData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<ComicUnfavorResponse, ComicUnfavorError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}/favor',
            ...options
        });
    }
    
    /**
     * Comiccbv.Favor
     */
    public static comicFavor<ThrowOnError extends boolean = false>(options: Options<ComicFavorData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ComicFavorResponse, ComicFavorError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}/favor',
            ...options
        });
    }
    
    /**
     * Comiccbv.Refresh
     */
    public static comicRefresh<ThrowOnError extends boolean = false>(options: Options<ComicRefreshData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ComicRefreshResponse, ComicRefreshError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}/refresh',
            ...options
        });
    }
    
    /**
     * Comiccbv.Rename
     */
    public static comicRename<ThrowOnError extends boolean = false>(options: Options<ComicRenameData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ComicRenameResponse2, ComicRenameError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}/rename',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class ComicpageService {
    /**
     * Comicpagecbv.Get
     */
    public static comicPageGet<ThrowOnError extends boolean = false>(options: Options<ComicPageGetData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, ComicPageGetError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}/pages/{page}',
            ...options
        });
    }
    
    /**
     * Comicpagecbv.Update Progress
     */
    public static comicPageUpdateProgress<ThrowOnError extends boolean = false>(options: Options<ComicPageUpdateProgressData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<ComicPageUpdateProgressResponse, ComicPageUpdateProgressError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}/progress',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Comicpagecbv.Like
     */
    public static comicPageLike<ThrowOnError extends boolean = false>(options: Options<ComicPageLikeData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, ComicPageLikeError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}/pages/{page}/like',
            ...options
        });
    }
    
    /**
     * Comicpagecbv.Set Cover
     */
    public static comicPageSetCover<ThrowOnError extends boolean = false>(options: Options<ComicPageSetCoverData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, ComicPageSetCoverError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/comics/{id}/pages/{page}/cover',
            ...options
        });
    }
    
}

export class VideosService {
    /**
     * Videocbv.Get All
     */
    public static videoGetAll<ThrowOnError extends boolean = false>(options?: Options<VideoGetAllData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<VideoGetAllResponse, VideoGetAllError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/videos',
            ...options
        });
    }
    
    /**
     * Videocbv.Delete
     */
    public static videoDelete<ThrowOnError extends boolean = false>(options: Options<VideoDeleteData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<VideoDeleteResponse, VideoDeleteError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/videos/{id}',
            ...options
        });
    }
    
    /**
     * Videocbv.Get
     */
    public static videoGet<ThrowOnError extends boolean = false>(options: Options<VideoGetData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<VideoGetResponse, VideoGetError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/videos/{id}',
            ...options
        });
    }
    
}

export class ImagesService {
    /**
     * Imagecbv.Get All
     */
    public static imageGetAll<ThrowOnError extends boolean = false>(options?: Options<ImageGetAllData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<ImageGetAllResponse, ImageGetAllError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images',
            ...options
        });
    }
    
    /**
     * Imagecbv.Delete
     */
    public static imageDelete<ThrowOnError extends boolean = false>(options: Options<ImageDeleteData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<ImageDeleteResponse, ImageDeleteError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}',
            ...options
        });
    }
    
    /**
     * Imagecbv.Get
     */
    public static imageGet<ThrowOnError extends boolean = false>(options: Options<ImageGetData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<ImageGetResponse, ImageGetError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}',
            ...options
        });
    }
    
    /**
     * Imagecbv.Detail
     */
    public static imageDetail<ThrowOnError extends boolean = false>(options: Options<ImageDetailData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<ImageDetailResponse2, ImageDetailError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}/detail',
            ...options
        });
    }
    
    /**
     * Imagecbv.Delete Page
     * Delete a single image file from an album.
     *
     * `page` is 1-based (page 1 == the album's first file), matching get_page.
     * Unlike comics (whose pages live inside an archive), image albums are
     * plain folders, so an individual file can be removed in place. The page
     * count and updateTime are refreshed; bumping updateTime invalidates the
     * page etags, since every page after the deleted one now maps to a
     * different file. The cover is only regenerated when the deleted page was
     * its source image, so a custom-set cover survives unrelated deletions.
     */
    public static imageDeletePage<ThrowOnError extends boolean = false>(options: Options<ImageDeletePageData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<ImageDeletePageResponse, ImageDeletePageError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}/pages/{page}',
            ...options
        });
    }
    
    /**
     * Imagecbv.Get Page
     */
    public static imageGetPage<ThrowOnError extends boolean = false>(options: Options<ImageGetPageData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, ImageGetPageError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}/pages/{page}',
            ...options
        });
    }
    
    /**
     * Imagecbv.Update Progress
     */
    public static imageUpdateProgress<ThrowOnError extends boolean = false>(options: Options<ImageUpdateProgressData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<ImageUpdateProgressResponse, ImageUpdateProgressError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}/progress',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Imagecbv.Unfavor
     */
    public static imageUnfavor<ThrowOnError extends boolean = false>(options: Options<ImageUnfavorData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<ImageUnfavorResponse, ImageUnfavorError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}/favor',
            ...options
        });
    }
    
    /**
     * Imagecbv.Favor
     */
    public static imageFavor<ThrowOnError extends boolean = false>(options: Options<ImageFavorData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ImageFavorResponse, ImageFavorError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}/favor',
            ...options
        });
    }
    
    /**
     * Imagecbv.Refresh
     */
    public static imageRefresh<ThrowOnError extends boolean = false>(options: Options<ImageRefreshData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ImageRefreshResponse, ImageRefreshError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}/refresh',
            ...options
        });
    }
    
    /**
     * Imagecbv.Rename
     */
    public static imageRename<ThrowOnError extends boolean = false>(options: Options<ImageRenameData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ImageRenameResponse2, ImageRenameError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}/rename',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Imagecbv.Set Cover
     */
    public static imageSetCover<ThrowOnError extends boolean = false>(options: Options<ImageSetCoverData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, ImageSetCoverError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}/pages/{page}/cover',
            ...options
        });
    }
    
    /**
     * Imagecbv.Convert
     * Package an image folder into a zip comic file and import it.
     *
     * The original images are stored verbatim (deflate-compressed) under
     * their existing filenames, so page order matches what the album shows.
     * The source folder is left untouched; the new comic is added to the
     * comic library and gets a cover generated like any scanned comic.
     */
    public static imageConvert<ThrowOnError extends boolean = false>(options: Options<ImageConvertData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ImageConvertResponse, ImageConvertError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/images/{id}/convert',
            ...options
        });
    }
    
}

export class SystemService {
    /**
     * Health Check
     */
    public static healthCheck<ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<HealthCheckResponse, HealthCheckError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/health',
            ...options
        });
    }
    
    /**
     * Scan Status
     * Live progress + metrics for the running scan (or the most recent one).
     */
    public static scanStatus<ThrowOnError extends boolean = false>(options?: Options<ScanStatusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<ScanStatusResponse2, ScanStatusError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/system/scan',
            ...options
        });
    }
    
    /**
     * Trigger Scan
     * Start a background scan to import new media files into the database.
     */
    public static triggerScan<ThrowOnError extends boolean = false>(options?: Options<TriggerScanData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<TriggerScanResponse, TriggerScanError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/system/scan',
            ...options
        });
    }
    
    /**
     * Tasks Status
     * Background task health: next scheduled scan and database backup state.
     */
    public static tasksStatus<ThrowOnError extends boolean = false>(options?: Options<TasksStatusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<TasksStatusResponse, TasksStatusError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/system/tasks',
            ...options
        });
    }
    
    /**
     * Trigger Backup
     */
    public static triggerBackup<ThrowOnError extends boolean = false>(options?: Options<TriggerBackupData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<TriggerBackupResponse, TriggerBackupError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/debug/backup-now',
            ...options
        });
    }
    
}