// This file is auto-generated by @hey-api/openapi-ts

/**
 * A lightweight utility class intended for use with simple message-returning endpoints.
 */
export type ApiMessage = {
    detail: string;
};

export type AuthStatusResponse = {
    required: boolean;
};

/**
 * Response for comic details
 */
export type ComicDetailResponse = {
    pageDetails: Array<ComicPageDetailResponse>;
};

export type ComicEntity = {
    id: number;
    size: number;
    name: string;
    path: string;
    updateTime: string;
    archived?: boolean;
    favorited?: boolean;
    missing?: boolean;
    lastViewedTime?: string | null;
    lastViewedPosition?: number;
    coverPosition?: number;
    entityUpdateTime?: string;
    page?: number;
};

/**
 * Response for comic page details
 */
export type ComicPageDetailResponse = {
    name: string;
};

/**
 * Request to rename a comic
 */
export type ComicRenameRequest = {
    name: string;
};

/**
 * Response for comic rename operation
 */
export type ComicRenameResponse = {
    name: string;
};

/**
 * Response for favor/unfavor operations
 */
export type FavorResponse = {
    favorited: boolean;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type HealthResponse = {
    status: string;
    message: string;
};

export type ImageDetailResponse = {
    pageDetails: Array<ImagePageDetailResponse>;
};

export type ImageEntity = {
    id: number;
    size: number;
    name: string;
    path: string;
    updateTime: string;
    archived?: boolean;
    favorited?: boolean;
    missing?: boolean;
    lastViewedTime?: string | null;
    lastViewedPosition?: number;
    coverPosition?: number;
    entityUpdateTime?: string;
    page?: number;
};

export type ImagePageDetailResponse = {
    name: string;
};

export type ImageRenameRequest = {
    name: string;
};

export type ImageRenameResponse = {
    name: string;
};

export type LoginRequest = {
    password: string;
};

export type LoginResponse = {
    token: string;
};

/**
 * Request to update reading progress
 */
export type ProgressRequest = {
    /**
     * 1-based page position
     */
    position: number;
};

/**
 * Response for reading progress update
 */
export type ProgressResponse = {
    position: number;
    lastViewedTime: string;
};

export type ScanResponse = {
    status: string;
    message: string;
};

export type ScanStatusResponse = {
    running: boolean;
    last_result?: {
        [key: string]: unknown;
    } | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type VideoEntity = {
    id: number;
    size: number;
    name: string;
    path: string;
    updateTime: string;
    archived?: boolean;
    favorited?: boolean;
    missing?: boolean;
    lastViewedTime?: string | null;
    lastViewedPosition?: number;
    coverPosition?: number;
    entityUpdateTime?: string;
    durationInSecond?: number;
};

export type MessageResponse = {
    msg: string;
};

export type StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/status';
};

export type StatusErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type StatusError = StatusErrors[keyof StatusErrors];

export type StatusResponses = {
    /**
     * Successful Response
     */
    200: AuthStatusResponse;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type ComicGetAllData = {
    body?: never;
    path?: never;
    query?: {
        fileMiss?: boolean;
        top?: number;
    };
    url: '/api/comics';
};

export type ComicGetAllErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicGetAllError = ComicGetAllErrors[keyof ComicGetAllErrors];

export type ComicGetAllResponses = {
    /**
     * Successful Response
     */
    200: Array<ComicEntity>;
};

export type ComicGetAllResponse = ComicGetAllResponses[keyof ComicGetAllResponses];

export type ComicDeleteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        permanent?: boolean;
    };
    url: '/api/comics/{id}';
};

export type ComicDeleteErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicDeleteError = ComicDeleteErrors[keyof ComicDeleteErrors];

export type ComicDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ComicGetData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/comics/{id}';
};

export type ComicGetErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicGetError = ComicGetErrors[keyof ComicGetErrors];

export type ComicGetResponses = {
    /**
     * Successful Response
     */
    200: ComicEntity;
};

export type ComicGetResponse = ComicGetResponses[keyof ComicGetResponses];

export type ComicDetailData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/comics/{id}/detail';
};

export type ComicDetailErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicDetailError = ComicDetailErrors[keyof ComicDetailErrors];

export type ComicDetailResponses = {
    /**
     * Successful Response
     */
    200: ComicDetailResponse;
};

export type ComicDetailResponse2 = ComicDetailResponses[keyof ComicDetailResponses];

export type ComicUnfavorData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/comics/{id}/favor';
};

export type ComicUnfavorErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicUnfavorError = ComicUnfavorErrors[keyof ComicUnfavorErrors];

export type ComicUnfavorResponses = {
    /**
     * Successful Response
     */
    200: FavorResponse;
};

export type ComicUnfavorResponse = ComicUnfavorResponses[keyof ComicUnfavorResponses];

export type ComicFavorData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/comics/{id}/favor';
};

export type ComicFavorErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicFavorError = ComicFavorErrors[keyof ComicFavorErrors];

export type ComicFavorResponses = {
    /**
     * Successful Response
     */
    200: FavorResponse;
};

export type ComicFavorResponse = ComicFavorResponses[keyof ComicFavorResponses];

export type ComicRefreshData = {
    body?: never;
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/comics/{id}/refresh';
};

export type ComicRefreshErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicRefreshError = ComicRefreshErrors[keyof ComicRefreshErrors];

export type ComicRefreshResponses = {
    /**
     * Successful Response
     */
    200: ComicEntity;
};

export type ComicRefreshResponse = ComicRefreshResponses[keyof ComicRefreshResponses];

export type ComicRenameData = {
    body: ComicRenameRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/comics/{id}/rename';
};

export type ComicRenameErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicRenameError = ComicRenameErrors[keyof ComicRenameErrors];

export type ComicRenameResponses = {
    /**
     * Successful Response
     */
    200: ComicRenameResponse;
};

export type ComicRenameResponse2 = ComicRenameResponses[keyof ComicRenameResponses];

export type ComicPageGetData = {
    body?: never;
    path: {
        id: number;
        page: number;
    };
    query?: {
        width?: number | null;
        token?: string | null;
    };
    url: '/api/comics/{id}/{page}';
};

export type ComicPageGetErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicPageGetError = ComicPageGetErrors[keyof ComicPageGetErrors];

export type ComicPageGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ComicPageUpdateProgressData = {
    body: ProgressRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/comics/{id}/progress';
};

export type ComicPageUpdateProgressErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicPageUpdateProgressError = ComicPageUpdateProgressErrors[keyof ComicPageUpdateProgressErrors];

export type ComicPageUpdateProgressResponses = {
    /**
     * Successful Response
     */
    200: ProgressResponse;
};

export type ComicPageUpdateProgressResponse = ComicPageUpdateProgressResponses[keyof ComicPageUpdateProgressResponses];

export type ComicPageLikeData = {
    body?: never;
    path: {
        id: number;
        page: number;
    };
    query?: never;
    url: '/api/comics/{id}/{page}/like';
};

export type ComicPageLikeErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicPageLikeError = ComicPageLikeErrors[keyof ComicPageLikeErrors];

export type ComicPageLikeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ComicPageSetCoverData = {
    body?: never;
    path: {
        id: number;
        page: number;
    };
    query?: never;
    url: '/api/comics/{id}/{page}/cover';
};

export type ComicPageSetCoverErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ComicPageSetCoverError = ComicPageSetCoverErrors[keyof ComicPageSetCoverErrors];

export type ComicPageSetCoverResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VideoGetAllData = {
    body?: never;
    path?: never;
    query?: {
        top?: number;
    };
    url: '/api/videos';
};

export type VideoGetAllErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type VideoGetAllError = VideoGetAllErrors[keyof VideoGetAllErrors];

export type VideoGetAllResponses = {
    /**
     * Successful Response
     */
    200: Array<VideoEntity>;
};

export type VideoGetAllResponse = VideoGetAllResponses[keyof VideoGetAllResponses];

export type VideoDeleteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        permanent?: boolean;
    };
    url: '/api/videos/{id}';
};

export type VideoDeleteErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type VideoDeleteError = VideoDeleteErrors[keyof VideoDeleteErrors];

export type VideoDeleteResponses = {
    /**
     * Successful Response
     */
    200: ApiMessage;
};

export type VideoDeleteResponse = VideoDeleteResponses[keyof VideoDeleteResponses];

export type VideoGetData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/videos/{id}';
};

export type VideoGetErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type VideoGetError = VideoGetErrors[keyof VideoGetErrors];

export type VideoGetResponses = {
    /**
     * Successful Response
     */
    200: VideoEntity;
};

export type VideoGetResponse = VideoGetResponses[keyof VideoGetResponses];

export type ImageGetAllData = {
    body?: never;
    path?: never;
    query?: {
        top?: number;
    };
    url: '/api/images';
};

export type ImageGetAllErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageGetAllError = ImageGetAllErrors[keyof ImageGetAllErrors];

export type ImageGetAllResponses = {
    /**
     * Successful Response
     */
    200: Array<ImageEntity>;
};

export type ImageGetAllResponse = ImageGetAllResponses[keyof ImageGetAllResponses];

export type ImageDeleteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/images/{id}';
};

export type ImageDeleteErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageDeleteError = ImageDeleteErrors[keyof ImageDeleteErrors];

export type ImageDeleteResponses = {
    /**
     * Successful Response
     */
    200: ApiMessage;
};

export type ImageDeleteResponse = ImageDeleteResponses[keyof ImageDeleteResponses];

export type ImageGetData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/images/{id}';
};

export type ImageGetErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageGetError = ImageGetErrors[keyof ImageGetErrors];

export type ImageGetResponses = {
    /**
     * Successful Response
     */
    200: ImageEntity;
};

export type ImageGetResponse = ImageGetResponses[keyof ImageGetResponses];

export type ImageDetailData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/images/{id}/detail';
};

export type ImageDetailErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageDetailError = ImageDetailErrors[keyof ImageDetailErrors];

export type ImageDetailResponses = {
    /**
     * Successful Response
     */
    200: ImageDetailResponse;
};

export type ImageDetailResponse2 = ImageDetailResponses[keyof ImageDetailResponses];

export type ImageGetPageData = {
    body?: never;
    path: {
        id: number;
        page: number;
    };
    query?: {
        width?: number | null;
        token?: string | null;
    };
    url: '/api/images/{id}/{page}';
};

export type ImageGetPageErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageGetPageError = ImageGetPageErrors[keyof ImageGetPageErrors];

export type ImageGetPageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImageUpdateProgressData = {
    body: ProgressRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/images/{id}/progress';
};

export type ImageUpdateProgressErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageUpdateProgressError = ImageUpdateProgressErrors[keyof ImageUpdateProgressErrors];

export type ImageUpdateProgressResponses = {
    /**
     * Successful Response
     */
    200: ProgressResponse;
};

export type ImageUpdateProgressResponse = ImageUpdateProgressResponses[keyof ImageUpdateProgressResponses];

export type ImageUnfavorData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/images/{id}/favor';
};

export type ImageUnfavorErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageUnfavorError = ImageUnfavorErrors[keyof ImageUnfavorErrors];

export type ImageUnfavorResponses = {
    /**
     * Successful Response
     */
    200: FavorResponse;
};

export type ImageUnfavorResponse = ImageUnfavorResponses[keyof ImageUnfavorResponses];

export type ImageFavorData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/images/{id}/favor';
};

export type ImageFavorErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageFavorError = ImageFavorErrors[keyof ImageFavorErrors];

export type ImageFavorResponses = {
    /**
     * Successful Response
     */
    200: FavorResponse;
};

export type ImageFavorResponse = ImageFavorResponses[keyof ImageFavorResponses];

export type ImageRefreshData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/images/{id}/refresh';
};

export type ImageRefreshErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageRefreshError = ImageRefreshErrors[keyof ImageRefreshErrors];

export type ImageRefreshResponses = {
    /**
     * Successful Response
     */
    200: ImageEntity;
};

export type ImageRefreshResponse = ImageRefreshResponses[keyof ImageRefreshResponses];

export type ImageRenameData = {
    body: ImageRenameRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/images/{id}/rename';
};

export type ImageRenameErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageRenameError = ImageRenameErrors[keyof ImageRenameErrors];

export type ImageRenameResponses = {
    /**
     * Successful Response
     */
    200: ImageRenameResponse;
};

export type ImageRenameResponse2 = ImageRenameResponses[keyof ImageRenameResponses];

export type ImageSetCoverData = {
    body?: never;
    path: {
        id: number;
        page: number;
    };
    query?: never;
    url: '/api/images/{id}/{page}/cover';
};

export type ImageSetCoverErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageSetCoverError = ImageSetCoverErrors[keyof ImageSetCoverErrors];

export type ImageSetCoverResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImageConvertData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/images/{id}/convert';
};

export type ImageConvertErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ImageConvertError = ImageConvertErrors[keyof ImageConvertErrors];

export type ImageConvertResponses = {
    /**
     * Successful Response
     */
    200: ComicEntity;
};

export type ImageConvertResponse = ImageConvertResponses[keyof ImageConvertResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type ScanStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/scan';
};

export type ScanStatusErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type ScanStatusError = ScanStatusErrors[keyof ScanStatusErrors];

export type ScanStatusResponses = {
    /**
     * Successful Response
     */
    200: ScanStatusResponse;
};

export type ScanStatusResponse2 = ScanStatusResponses[keyof ScanStatusResponses];

export type TriggerScanData = {
    body?: never;
    path?: never;
    query?: {
        media_type?: 'comics' | 'videos' | 'images' | 'all';
    };
    url: '/api/system/scan';
};

export type TriggerScanErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type TriggerScanError = TriggerScanErrors[keyof TriggerScanErrors];

export type TriggerScanResponses = {
    /**
     * Successful Response
     */
    200: ScanResponse;
};

export type TriggerScanResponse = TriggerScanResponses[keyof TriggerScanResponses];

export type TriggerBackupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/backup-now';
};

export type TriggerBackupErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Unauthorized
     */
    401: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
    /**
     * Validation Error
     */
    422: MessageResponse;
    /**
     * Internal Server Error
     */
    500: MessageResponse;
};

export type TriggerBackupError = TriggerBackupErrors[keyof TriggerBackupErrors];

export type TriggerBackupResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type TriggerBackupResponse = TriggerBackupResponses[keyof TriggerBackupResponses];

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8001' | (string & {});
};